allowBuilds:
  lefthook: true
  nx: false
  unrs-resolver: true
catalog:
  "@storm-software/config": ^1.138.19
  "@storm-software/config-tools": ^1.190.82
  "@storm-software/cspell": ^0.46.150
  "@storm-software/eslint": ^0.170.115
  "@storm-software/git-tools": ^2.131.90
  "@storm-software/linting-tools": ^1.134.12
  "@storm-software/markdownlint": ^0.30.238
  "@storm-software/pnpm-tools": ^0.7.93
  "@storm-software/prettier": ^0.59.135
  "@storm-software/tsconfig": ^0.48.149
  unrs-resolver: ^1.12.2
  zx: ^8.8.5
  prettier: ^3.9.4
  rimraf: ^6.1.3
  lefthook: ^1.13.6
  eslint: ^10.6.0
  copyfiles: ^2.4.1
shamefullyHoist: true
engineStrict: true
fetchTimeout: 240000
dedupeDirectDeps: true
dedupePeerDependents: true
cleanupUnusedCatalogs: true
